[package]
name = "toolchain"
version = "0.0.1"
edition = "2018"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.20.0", features = ["macros"] }
[profile.dev]
incremental = true

